{% set name = "up42-py" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4289e2a70a38266941a0389f4bd235d9f5f7de178390df9524ea932d63792581

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  build:
    - pip
    - python >=3.9, <4
    - setuptools
    - wheel
  host:
    - pip
    - python >=3.9, <4
    - poetry
  run:
    - branca
    - folium
    - matplotlib-base
    - geojson ==3.1.0
    - geopandas <1
    - python >=3.9, <4
    - rasterio
    - requests ==2.31.0
    - tqdm ==4.66.0
    - tenacity ==8.4.1
    - pystac-client >=0.7.2, <0.8.0
    - shapely
    - pandas
    - pystac
    - urllib3

test:
  imports:
    - up42
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/up42/up42-py
  summary: Python SDK for UP42
  license: MIT
  license_file: LICENSE
  doc_url: https://sdk.up42.com
  dev_url: https://github.com/up42/up42-py

extra:
  recipe-maintainers:
    - andher1802
